# Generated by Django 5.0.3 on 2024-04-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicesEval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverRecontreSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('libelle', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_evenement', models.CharField(max_length=300, unique=True)),
                ('edition', models.CharField(max_length=300)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('inscription_limite', models.IntegerField(default=100)),
                ('decription', models.TextField(blank=True, null=True)),
                ('baniere_image', models.ImageField(blank=True, null=True, upload_to='evements/baniere/')),
                ('baniere_image_2', models.ImageField(blank=True, null=True, upload_to='evements/baniere/')),
            ],
            options={
                'verbose_name': 'Evénements',
                'verbose_name_plural': 'Evénements',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_insc', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('residence', models.CharField(choices=[('BRAZZAVILLE', 'Brazzaville'), ('POINTE-NOIRE', 'Pointe-Noire')], default='BRAZZAVILLE', max_length=200)),
                ('phoneNumber', models.CharField(db_index=True, max_length=200)),
                ('commment_avez_vous_entendu_parler_des_rencontres_ELLE', models.CharField(choices=[('PROSPECTION', 'Prospection'), ('RESEAUX-SOCIAUX', 'Réseaux sociaux'), ('BOUCHE-A-OREILLE', 'Bouche à oreille')], default='PROSPECTION', max_length=200)),
                ('connaissez_vous_archer_Capital', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='NON', max_length=10)),
                ('recevoir_infos', models.BooleanField(default=False)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverRencontre.evenements')),
                ('proffession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesEval.profession')),
                ('secteurActivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesEval.secteuractivite')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('que_pensez_vous_du_concept', models.CharField(blank=True, max_length=300, null=True)),
                ('quelles_etaient_vos_attentes', models.CharField(blank=True, max_length=300, null=True)),
                ('vos_attentes_ont_elles_ete_comblees', models.CharField(blank=True, max_length=300, null=True)),
                ('les_themes_abordes_ont_ils_ete_pertinents_selon_vous', models.CharField(blank=True, max_length=300, null=True)),
                ('souhaiteriez_vous_participer_a_autres_evenements_de_ce_type', models.CharField(blank=True, max_length=300, null=True)),
                ('quels_sont_les_sujets_que_vous_aimeriez_voir_abordes_lors_des_prochaines_rencontres', models.TextField(blank=True, null=True)),
                ('inviteriez_vous_une_amie_prochainement', models.CharField(blank=True, max_length=300, null=True)),
                ('avez_vous_besoin_un_accompagnement_personalise', models.CharField(blank=True, max_length=300, null=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='coverRencontre.evenements')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverRencontre.participants')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
    ]
